### ISSUE TITLE
Unable to Enlarge Transfer Order Item Image by Clicking on Image Icon

### ISSUE THREAD

**Issue by Adameddy26** [hotwax/fulfillment#420] opened 2024-02-23 10:46 UTC
## Current behavior
Clicking on the image icon fails to enlarge the image or open it in a larger view, preventing users from closely inspecting item details.

## Expected behavior
Upon clicking the image icon, the associated item image should enlarge or open in a larger view, allowing users to inspect item details more closely for accurate verification and processing of transfer orders.

## Steps to reproduce the issue
Navigate to a transfer order item that includes an associated image.
Locate the image icon or thumbnail representing the item image.
Attempt to enlarge the image by clicking on the icon or thumbnail.
Observe that the image does not enlarge or open in a larger view as expected.

## Environment details
- App version: TRANSFER-ORDER-UI-D9CDF5B
- App environment: UAT

## Additional information
https://jam.dev/c/137adc59-878f-4182-971e-5d105ed6357f

**Comment by dt2patel** [comment] 2024-07-19 10:48
duplicate of #283

**Closed by dt2patel** 2024-07-19 10:48 UTC
Labels: enhancement
